# Generated by Django 3.2.9 on 2021-11-30 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote', '0003_alter_vote_vote_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='area',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='candidates',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='vote_by',
        ),
        migrations.AddField(
            model_name='vote',
            name='area',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='vote.voterarea'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voterarea',
            name='candidates',
            field=models.ManyToManyField(blank=True, to='vote.Candidate'),
        ),
        migrations.CreateModel(
            name='VoteResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='vote.candidate')),
                ('vote', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='vote.vote')),
                ('vote_by', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
